from data.cards import CardData

SAVE_GAME_FOLDER = "GameSaves"

PLAYER_STARTING_HEALTH = 100
PLAYER_STARTING_CARDS = CardData.load_starting_cards()

# Layer draw order constants
DRAW_ORDER_BACKGROUND = -1000
DRAW_ORDER_MIDGROUND = 0
DRAW_ORDER_MIDGROUND_UI = 500
DRAW_ORDER_EFFECTS = 1000
DRAW_ORDER_FOREGROUND = 1500
DRAW_ORDER_FOREGROUND_UI = 2000
DRAW_ORDER_OVERLAY_UI = 2500

# Game object draw order constants
LAYER_DEFAULT = DRAW_ORDER_MIDGROUND
LAYER_ENEMY = DRAW_ORDER_MIDGROUND
LAYER_EFFECTS = LAYER_ENEMY + 50
LAYER_TARGETED_ENEMY_ICON = DRAW_ORDER_MIDGROUND_UI
LAYER_CARD_REWARD_TEXT = DRAW_ORDER_OVERLAY_UI
LAYER_CARD_REWARD = DRAW_ORDER_OVERLAY_UI
LAYER_PLAYER_HAND = DRAW_ORDER_FOREGROUND
LAYER_PLAYER_UI_BACKGROUND = DRAW_ORDER_OVERLAY_UI
LAYER_PLAYER_UI_TEXT = DRAW_ORDER_OVERLAY_UI + 1
LAYER_UI_EFFECTS = LAYER_PLAYER_UI_TEXT + 50
LAYER_OVERRIDE_BG = 1000000
LAYER_OVERRIDE_FG = LAYER_OVERRIDE_BG + 1
