
BACKGROUND_DRAW_ORDER = -1000
MIDGROUND_DRAW_ORDER = 0
MIDGROUND_UI_DRAW_ORDER = 500
EFFECTS_DRAW_ORDER = 1000
FOREGROUND_DRAW_ORDER = 1500
FOREGROUND_UI_DRAW_ORDER = 2000
OVERLAY_UI_DRAW_ORDER = 2500

DEFAULT_DRAW_ORDER = MIDGROUND_DRAW_ORDER
ENEMY_DRAW_ORDER = MIDGROUND_DRAW_ORDER
TARGETED_ENEMY_ICON_DRAW_ORDER = MIDGROUND_UI_DRAW_ORDER
CARD_REWARD_TEXT_DRAW_ORDER = OVERLAY_UI_DRAW_ORDER
CARD_REWARD_DRAW_ORDER = OVERLAY_UI_DRAW_ORDER
PLAYER_HAND_DRAW_ORDER = FOREGROUND_DRAW_ORDER
PLAYER_UI_BACKGROUND_DRAW_ORDER = OVERLAY_UI_DRAW_ORDER
PLAYER_UI_TEXT_DRAW_ORDER = OVERLAY_UI_DRAW_ORDER + 1
OVERRIDE_DRAW_ORDER_BG = 1000000
OVERRIDE_DRAW_ORDER_FG = OVERRIDE_DRAW_ORDER_BG + 1
